update petel_schema.councils set long_name ='עריית אום אל-פחם', district_id=1, council_type_id=1 where council_code = 2710;
update petel_schema.councils set long_name ='עריית אופקים', district_id=2, council_type_id=1 where council_code = 31;
update petel_schema.councils set long_name ='עריית אור יהודה', district_id=3, council_type_id=1 where council_code = 2400;
update petel_schema.councils set long_name ='עריית אור עקיבא', district_id=1, council_type_id=1 where council_code = 1020;
update petel_schema.councils set long_name ='עריית אילת', district_id=2, council_type_id=1 where council_code = 2600;
update petel_schema.councils set long_name ='עריית טירה', district_id=4, council_type_id=1 where council_code = 2720;
update petel_schema.councils set long_name ='עריית אלעד', district_id=4, council_type_id=1 where council_code = 1309;
update petel_schema.councils set long_name ='עריית אריאל', district_id=5, council_type_id=1 where council_code = 3570;
update petel_schema.councils set long_name ='עריית אשדוד', district_id=2, council_type_id=1 where council_code = 70;
update petel_schema.councils set long_name ='עריית אשקלון', district_id=2, council_type_id=1 where council_code = 7100;
update petel_schema.councils set long_name ='עריית באקה אל-גרביה', district_id=1, council_type_id=1 where council_code = 6000;
update petel_schema.councils set long_name ='עריית באר שבע', district_id=2, council_type_id=1 where council_code = 9000;
update petel_schema.councils set long_name ='עריית בית שמש', district_id=6, council_type_id=1 where council_code = 2610;
update petel_schema.councils set long_name ='עריית בית שאן', district_id=7, council_type_id=1 where council_code = 9200;
update petel_schema.councils set long_name ='עריית ביתר עילית', district_id=5, council_type_id=1 where council_code = 3780;
update petel_schema.councils set long_name ='עריית בני ברק', district_id=3, council_type_id=1 where council_code = 6100;
update petel_schema.councils set long_name ='עריית בת ים', district_id=3, council_type_id=1 where council_code = 6200;
update petel_schema.councils set long_name ='עריית גבעת שמואל', district_id=4, council_type_id=1 where council_code = 681;
update petel_schema.councils set long_name ='עריית גבעתיים', district_id=3, council_type_id=1 where council_code = 6300;
update petel_schema.councils set long_name ='עריית דימונה', district_id=2, council_type_id=1 where council_code = 2200;
update petel_schema.councils set long_name ='עריית הוד השרון', district_id=4, council_type_id=1 where council_code = 9700;
update petel_schema.councils set long_name ='עריית הרצלייה', district_id=3, council_type_id=1 where council_code = 6400;
update petel_schema.councils set long_name ='עריית חדרה', district_id=1, council_type_id=1 where council_code = 6500;
update petel_schema.councils set long_name ='עריית חולון', district_id=3, council_type_id=1 where council_code = 6600;
update petel_schema.councils set long_name ='עריית חיפה', district_id=1, council_type_id=1 where council_code = 4000;
update petel_schema.councils set long_name ='עריית טבריה', district_id=7, council_type_id=1 where council_code = 6700;
update petel_schema.councils set long_name ='עריית טייבה', district_id=4, council_type_id=1 where council_code = 2730;
update petel_schema.councils set long_name ='עריית טירת כרמל', district_id=1, council_type_id=1 where council_code = 2100;
update petel_schema.councils set long_name ='עריית טמרה', district_id=7, council_type_id=1 where council_code = 8900;
update petel_schema.councils set long_name ='עריית יבנה', district_id=4, council_type_id=1 where council_code = 2660;
update petel_schema.councils set long_name ='עריית יהוד-מונוסון', district_id=4, council_type_id=1 where council_code = 9400;
update petel_schema.councils set long_name ='עריית יקנעם עילית', district_id=7, council_type_id=1 where council_code = 240;
update petel_schema.councils set long_name ='עריית ירושלים', district_id=6, council_type_id=1 where council_code = 3000;
update petel_schema.councils set long_name ='עריית כפר יונה', district_id=4, council_type_id=1 where council_code = 168;
update petel_schema.councils set long_name ='עריית כפר סבא', district_id=4, council_type_id=1 where council_code = 6900;
update petel_schema.councils set long_name ='עריית כפר קאסם', district_id=4, council_type_id=1 where council_code = 634;
update petel_schema.councils set long_name ='עריית כרמיאל', district_id=7, council_type_id=1 where council_code = 1139;
update petel_schema.councils set long_name ='עריית לוד', district_id=4, council_type_id=1 where council_code = 7000;
update petel_schema.councils set long_name ='עריית מגדל העמק', district_id=7, council_type_id=1 where council_code = 874;
update petel_schema.councils set long_name ='עריית מודיעין-מכבים-רעות', district_id=4, council_type_id=1 where council_code = 1200;
update petel_schema.councils set long_name ='עריית מודיעין עילית', district_id=5, council_type_id=1 where council_code = 3797;
update petel_schema.councils set long_name ='עריית מעלה אדומים', district_id=5, council_type_id=1 where council_code = 3616;
update petel_schema.councils set long_name ='עריית מעלות-תרשיחא', district_id=7, council_type_id=1 where council_code = 1063;
update petel_schema.councils set long_name ='עריית נהרייה', district_id=7, council_type_id=1 where council_code = 9100;
update petel_schema.councils set long_name ='עריית נס ציונה', district_id=4, council_type_id=1 where council_code = 7200;
update petel_schema.councils set long_name ='עריית נצרת', district_id=7, council_type_id=1 where council_code = 7300;
update petel_schema.councils set long_name ='עריית נוף הגליל', district_id=7, council_type_id=1 where council_code = 1061;
update petel_schema.councils set long_name ='עריית נשר', district_id=1, council_type_id=1 where council_code = 2500;
update petel_schema.councils set long_name ='עריית נתיבות', district_id=2, council_type_id=1 where council_code = 246;
update petel_schema.councils set long_name ='עריית נתניה', district_id=4, council_type_id=1 where council_code = 7400;
update petel_schema.councils set long_name ='עריית סח''נין', district_id=7, council_type_id=1 where council_code = 7500;
update petel_schema.councils set long_name ='עריית עפולה', district_id=7, council_type_id=1 where council_code = 7700;
update petel_schema.councils set long_name ='עריית עראבה', district_id=7, council_type_id=1 where council_code = 531;
update petel_schema.councils set long_name ='עריית ערד', district_id=2, council_type_id=1 where council_code = 2560;
update petel_schema.councils set long_name ='עריית פתח תקווה', district_id=4, council_type_id=1 where council_code = 7900;
update petel_schema.councils set long_name ='עריית צפת', district_id=7, council_type_id=1 where council_code = 8000;
update petel_schema.councils set long_name ='עריית קלנסווה', district_id=4, council_type_id=1 where council_code = 638;
update petel_schema.councils set long_name ='עריית קריית אונו', district_id=3, council_type_id=1 where council_code = 2620;
update petel_schema.councils set long_name ='עריית קריית אתא', district_id=1, council_type_id=1 where council_code = 6800;
update petel_schema.councils set long_name ='עריית קריית ביאליק', district_id=1, council_type_id=1 where council_code = 9500;
update petel_schema.councils set long_name ='עריית קריית גת', district_id=2, council_type_id=1 where council_code = 2630;
update petel_schema.councils set long_name ='עריית קריית ים', district_id=1, council_type_id=1 where council_code = 9600;
update petel_schema.councils set long_name ='עריית קריית מוצקין', district_id=1, council_type_id=1 where council_code = 8200;
update petel_schema.councils set long_name ='עריית קריית מלאכי', district_id=2, council_type_id=1 where council_code = 1034;
update petel_schema.councils set long_name ='עריית קריית שמונה', district_id=7, council_type_id=1 where council_code = 2800;
update petel_schema.councils set long_name ='עריית ראש העין', district_id=4, council_type_id=1 where council_code = 2640;
update petel_schema.councils set long_name ='עריית ראשון לציון', district_id=4, council_type_id=1 where council_code = 8300;
update petel_schema.councils set long_name ='עריית רהט', district_id=2, council_type_id=1 where council_code = 1161;
update petel_schema.councils set long_name ='עריית רחובות', district_id=4, council_type_id=1 where council_code = 8400;
update petel_schema.councils set long_name ='עריית רמלה', district_id=4, council_type_id=1 where council_code = 8500;
update petel_schema.councils set long_name ='עריית רמת גן', district_id=3, council_type_id=1 where council_code = 8600;
update petel_schema.councils set long_name ='עריית רמת השרון', district_id=3, council_type_id=1 where council_code = 2650;
update petel_schema.councils set long_name ='עריית רעננה', district_id=4, council_type_id=1 where council_code = 8700;
update petel_schema.councils set long_name ='עריית שדרות', district_id=2, council_type_id=1 where council_code = 1031;
update petel_schema.councils set long_name ='עריית שפרעם', district_id=7, council_type_id=1 where council_code = 8800;
update petel_schema.councils set long_name ='עריית תל אביב -יפו', district_id=3, council_type_id=1 where council_code = 5000;
update petel_schema.councils set long_name ='עריית באר יעקב', district_id=4, council_type_id=1 where council_code = 2530;
update petel_schema.councils set long_name ='עריית גני תקווה', district_id=4, council_type_id=1 where council_code = 229;
update petel_schema.councils set long_name ='עריית חריש', district_id=1, council_type_id=1 where council_code = 1247;
update petel_schema.councils set long_name ='עריית כפר קרע', district_id=1, council_type_id=1 where council_code = 654;
update petel_schema.councils set long_name ='עריית מגאר', district_id=7, council_type_id=1 where council_code = 481;
update petel_schema.councils set long_name ='עריית עכו', district_id=5, council_type_id=1 where council_code = 7600;
update petel_schema.councils set long_name ='עריית עין קנייא', district_id=7, council_type_id=2 where council_code = 4502;
update petel_schema.councils set long_name ='מועצה מקומית  אבו גוש', district_id=6, council_type_id=2 where council_code = 472;
update petel_schema.councils set long_name ='מועצה מקומית  אבו סנאן', district_id=7, council_type_id=2 where council_code = 473;
update petel_schema.councils set long_name ='מועצה מקומית  אבן יהודה', district_id=4, council_type_id=2 where council_code = 182;
update petel_schema.councils set long_name ='מועצה מקומית  אורנית', district_id=5, council_type_id=2 where council_code = 3760;
update petel_schema.councils set long_name ='מועצה מקומית  אזור', district_id=3, council_type_id=2 where council_code = 565;
update petel_schema.councils set long_name ='מועצה מקומית  אכסאל', district_id=7, council_type_id=2 where council_code = 478;
update petel_schema.councils set long_name ='מועצה מקומית  אעבלין', district_id=7, council_type_id=2 where council_code = 529;
update petel_schema.councils set long_name ='מועצה מקומית  ע''ג''ר', district_id=7, council_type_id=2 where council_code = 4501;
update petel_schema.councils set long_name ='מועצה מקומית  אליכין', district_id=4, council_type_id=2 where council_code = 41;
update petel_schema.councils set long_name ='מועצה מקומית  אלפי מנשה', district_id=5, council_type_id=2 where council_code = 3750;
update petel_schema.councils set long_name ='מועצה מקומית  אלקנה', district_id=5, council_type_id=2 where council_code = 3560;
update petel_schema.councils set long_name ='מועצה מקומית  אפרת', district_id=5, council_type_id=2 where council_code = 3650;
update petel_schema.councils set long_name ='מועצה מקומית  בועיינה-נוג''ידאת', district_id=7, council_type_id=2 where council_code = 482;
update petel_schema.councils set long_name ='מועצה מקומית  בוקעאתא', district_id=7, council_type_id=2 where council_code = 4001;
update petel_schema.councils set long_name ='מועצה מקומית  בענה', district_id=7, council_type_id=2 where council_code = 483;
update petel_schema.councils set long_name ='מועצה מקומית  ביר אל-מכסור', district_id=7, council_type_id=2 where council_code = 998;
update petel_schema.councils set long_name ='מועצה מקומית  בית ג''ן', district_id=7, council_type_id=2 where council_code = 480;
update petel_schema.councils set long_name ='מועצה מקומית  בית אל', district_id=5, council_type_id=2 where council_code = 3574;
update petel_schema.councils set long_name ='מועצה מקומית  בית אריה-עופרים', district_id=5, council_type_id=2 where council_code = 3652;
update petel_schema.councils set long_name ='מועצה מקומית  בית דגן', district_id=4, council_type_id=2 where council_code = 466;
update petel_schema.councils set long_name ='מועצה מקומית  בני עי"ש', district_id=4, council_type_id=2 where council_code = 1066;
update petel_schema.councils set long_name ='מועצה מקומית  בנימינה-גבעת עדה', district_id=1, council_type_id=2 where council_code = 9800;
update petel_schema.councils set long_name ='מועצה מקומית  בסמ"ה', district_id=1, council_type_id=2 where council_code = 1326;
update petel_schema.councils set long_name ='מועצה מקומית  בסמת טבעון', district_id=7, council_type_id=2 where council_code = 944;
update petel_schema.councils set long_name ='מועצה מקומית  ג''דיידה-מכר', district_id=7, council_type_id=2 where council_code = 1292;
update petel_schema.councils set long_name ='מועצה מקומית  ג''ולס', district_id=7, council_type_id=2 where council_code = 485;
update petel_schema.councils set long_name ='מועצה מקומית  ג''סר א-זרקא', district_id=1, council_type_id=2 where council_code = 541;
update petel_schema.councils set long_name ='מועצה מקומית  ג''לג''וליה', district_id=4, council_type_id=2 where council_code = 627;
update petel_schema.councils set long_name ='מועצה מקומית  ג''ת', district_id=1, council_type_id=2 where council_code = 628;
update petel_schema.councils set long_name ='מועצה מקומית  גבעת זאב', district_id=5, council_type_id=2 where council_code = 3730;
update petel_schema.councils set long_name ='מועצה מקומית  גדרה', district_id=4, council_type_id=2 where council_code = 2550;
update petel_schema.councils set long_name ='מועצה מקומית  ג''ש (גוש חלב)', district_id=7, council_type_id=2 where council_code = 487;
update petel_schema.councils set long_name ='מועצה מקומית  גן יבנה', district_id=4, council_type_id=2 where council_code = 166;
update petel_schema.councils set long_name ='מועצה מקומית  דבורייה', district_id=7, council_type_id=2 where council_code = 489;
update petel_schema.councils set long_name ='מועצה מקומית  דייר חנא', district_id=7, council_type_id=2 where council_code = 492;
update petel_schema.councils set long_name ='מועצה מקומית  דייר אל-אסד', district_id=7, council_type_id=2 where council_code = 490;
update petel_schema.councils set long_name ='מועצה מקומית  דאלית אל-כרמל', district_id=1, council_type_id=2 where council_code = 494;
update petel_schema.councils set long_name ='מועצה מקומית  הר אדר', district_id=5, council_type_id=2 where council_code = 3769;
update petel_schema.councils set long_name ='מועצה מקומית  זכרון יעקב', district_id=1, council_type_id=2 where council_code = 9300;
update petel_schema.councils set long_name ='מועצה מקומית  זמר', district_id=4, council_type_id=2 where council_code = 1290;
update petel_schema.councils set long_name ='מועצה מקומית  זרזיר', district_id=7, council_type_id=2 where council_code = 975;
update petel_schema.councils set long_name ='מועצה מקומית  חורה', district_id=2, council_type_id=2 where council_code = 1303;
update petel_schema.councils set long_name ='מועצה מקומית  חורפיש', district_id=7, council_type_id=2 where council_code = 496;
update petel_schema.councils set long_name ='מועצה מקומית  חצור הגלילית', district_id=7, council_type_id=2 where council_code = 2034;
update petel_schema.councils set long_name ='מועצה מקומית  טובא-זנגרייה', district_id=7, council_type_id=2 where council_code = 962;
update petel_schema.councils set long_name ='מועצה מקומית  טורעאן', district_id=7, council_type_id=2 where council_code = 498;
update petel_schema.councils set long_name ='מועצה מקומית  יבנאל', district_id=7, council_type_id=2 where council_code = 46;
update petel_schema.councils set long_name ='מועצה מקומית  יאנוח-ג''ת', district_id=7, council_type_id=2 where council_code = 1295;
update petel_schema.councils set long_name ='מועצה מקומית  יסוד המעלה', district_id=7, council_type_id=2 where council_code = 29;
update petel_schema.councils set long_name ='מועצה מקומית  יפיע', district_id=7, council_type_id=2 where council_code = 499;
update petel_schema.councils set long_name ='מועצה מקומית  ירוחם', district_id=2, council_type_id=2 where council_code = 831;
update petel_schema.councils set long_name ='מועצה מקומית  ירכא', district_id=7, council_type_id=2 where council_code = 502;
update petel_schema.councils set long_name ='מועצה מקומית  כאבול', district_id=7, council_type_id=2 where council_code = 504;
update petel_schema.councils set long_name ='מועצה מקומית  כאוכב אבו אל-היג''א', district_id=7, council_type_id=2 where council_code = 505;
update petel_schema.councils set long_name ='מועצה מקומית  כוכב יאיר', district_id=4, council_type_id=2 where council_code = 1224;
update petel_schema.councils set long_name ='מועצה מקומית  כסיפה', district_id=2, council_type_id=2 where council_code = 1059;
update petel_schema.councils set long_name ='מועצה מקומית  כסרא-סמיע', district_id=7, council_type_id=2 where council_code = 1296;
update petel_schema.councils set long_name ='מועצה מקומית  כעביה-טבאש-חג''אג''רה', district_id=7, council_type_id=2 where council_code = 978;
update petel_schema.councils set long_name ='מועצה מקומית  כפר ברא', district_id=4, council_type_id=2 where council_code = 633;
update petel_schema.councils set long_name ='מועצה מקומית  כפר כנא', district_id=7, council_type_id=2 where council_code = 509;
update petel_schema.councils set long_name ='מועצה מקומית  כפר ורדים', district_id=7, council_type_id=2 where council_code = 1263;
update petel_schema.councils set long_name ='מועצה מקומית  כפר יאסיף', district_id=7, council_type_id=2 where council_code = 507;
update petel_schema.councils set long_name ='מועצה מקומית  כפר מנדא', district_id=7, council_type_id=2 where council_code = 510;
update petel_schema.councils set long_name ='מועצה מקומית  כפר כמא', district_id=7, council_type_id=2 where council_code = 508;
update petel_schema.councils set long_name ='מועצה מקומית  כפר שמריהו', district_id=3, council_type_id=2 where council_code = 267;
update petel_schema.councils set long_name ='מועצה מקומית  כפר תבור', district_id=7, council_type_id=2 where council_code = 47;
update petel_schema.councils set long_name ='מועצה מקומית  להבים', district_id=2, council_type_id=2 where council_code = 1271;
update petel_schema.councils set long_name ='מועצה מקומית  לקיה', district_id=2, council_type_id=2 where council_code = 1060;
update petel_schema.councils set long_name ='מועצה מקומית  מבשרת ציון', district_id=6, council_type_id=2 where council_code = 1015;
update petel_schema.councils set long_name ='מועצה מקומית  מג''ד אל-כרום', district_id=7, council_type_id=2 where council_code = 516;
update petel_schema.councils set long_name ='מועצה מקומית  מג''דל שמס', district_id=7, council_type_id=2 where council_code = 4201;
update petel_schema.councils set long_name ='מועצה מקומית  מגדל', district_id=7, council_type_id=2 where council_code = 65;
update petel_schema.councils set long_name ='מועצה מקומית  מזכרת בתיה', district_id=4, council_type_id=2 where council_code = 28;
update petel_schema.councils set long_name ='מועצה מקומית  מזרעה', district_id=7, council_type_id=2 where council_code = 517;
update petel_schema.councils set long_name ='מועצה מקומית  מטולה', district_id=7, council_type_id=2 where council_code = 43;
update petel_schema.councils set long_name ='מועצה מקומית  מיתר', district_id=2, council_type_id=2 where council_code = 1268;
update petel_schema.councils set long_name ='מועצה מקומית  מסעדה', district_id=7, council_type_id=2 where council_code = 4203;
update petel_schema.councils set long_name ='מועצה מקומית  מעיליא', district_id=7, council_type_id=2 where council_code = 518;
update petel_schema.councils set long_name ='מועצה מקומית  מעלה אפרים', district_id=5, council_type_id=2 where council_code = 3608;
update petel_schema.councils set long_name ='מועצה מקומית  מעלה עירון', district_id=1, council_type_id=2 where council_code = 1327;
update petel_schema.councils set long_name ='מועצה מקומית  מצפה רמון', district_id=2, council_type_id=2 where council_code = 99;
update petel_schema.councils set long_name ='מועצה מקומית  משהד', district_id=7, council_type_id=2 where council_code = 520;
update petel_schema.councils set long_name ='מועצה מקומית  נחף', district_id=7, council_type_id=2 where council_code = 522;
update petel_schema.councils set long_name ='מועצה מקומית  סאג''ור', district_id=7, council_type_id=2 where council_code = 525;
update petel_schema.councils set long_name ='מועצה מקומית  סביון', district_id=4, council_type_id=2 where council_code = 587;
update petel_schema.councils set long_name ='מועצה מקומית  עומר', district_id=2, council_type_id=2 where council_code = 666;
update petel_schema.councils set long_name ='מועצה מקומית  עספיא', district_id=1, council_type_id=2 where council_code = 534;
update petel_schema.councils set long_name ='מועצה מקומית  עיילבון', district_id=7, council_type_id=2 where council_code = 530;
update petel_schema.councils set long_name ='מועצה מקומית  עילוט', district_id=7, council_type_id=2 where council_code = 511;
update petel_schema.councils set long_name ='מועצה מקומית  עמנואל', district_id=7, council_type_id=2 where council_code = 3660;
update petel_schema.councils set long_name ='מועצה מקומית  עין מאהל', district_id=7, council_type_id=2 where council_code = 532;
update petel_schema.councils set long_name ='מועצה מקומית  ערערה', district_id=1, council_type_id=2 where council_code = 637;
update petel_schema.councils set long_name ='מועצה מקומית  ערערה-בנגב', district_id=2, council_type_id=2 where council_code = 1192;
update petel_schema.councils set long_name ='מועצה מקומית  פוריידיס', district_id=1, council_type_id=2 where council_code = 537;
update petel_schema.councils set long_name ='מועצה מקומית  פסוטה', district_id=7, council_type_id=2 where council_code = 535;
update petel_schema.councils set long_name ='מועצה מקומית  פקיעין (בוקייעה)', district_id=7, council_type_id=2 where council_code = 536;
update petel_schema.councils set long_name ='מועצה מקומית  פרדס חנה-כרכור', district_id=1, council_type_id=2 where council_code = 7800;
update petel_schema.councils set long_name ='מועצה מקומית  פרדסייה', district_id=4, council_type_id=2 where council_code = 171;
update petel_schema.councils set long_name ='מועצה מקומית  קדומים', district_id=5, council_type_id=2 where council_code = 3557;
update petel_schema.councils set long_name ='מועצה מקומית  קדימה-צורן', district_id=4, council_type_id=2 where council_code = 195;
update petel_schema.councils set long_name ='מועצה מקומית  קצרין', district_id=7, council_type_id=2 where council_code = 4100;
update petel_schema.councils set long_name ='מועצה מקומית  קריית ארבע', district_id=5, council_type_id=2 where council_code = 3611;
update petel_schema.councils set long_name ='מועצה מקומית  קריית טבעון', district_id=1, council_type_id=2 where council_code = 2300;
update petel_schema.councils set long_name ='מועצה מקומית  קריית יערים', district_id=6, council_type_id=2 where council_code = 1137;
update petel_schema.councils set long_name ='מועצה מקומית  קריית עקרון', district_id=4, council_type_id=2 where council_code = 469;
update petel_schema.councils set long_name ='מועצה מקומית  קרני שומרון', district_id=5, council_type_id=2 where council_code = 3640;
update petel_schema.councils set long_name ='מועצה מקומית  ראמה', district_id=7, council_type_id=2 where council_code = 543;
update petel_schema.councils set long_name ='מועצה מקומית  ראש פינה', district_id=7, council_type_id=2 where council_code = 26;
update petel_schema.councils set long_name ='מועצה מקומית  ריינה', district_id=7, council_type_id=2 where council_code = 542;
update petel_schema.councils set long_name ='מועצה מקומית  רכסים', district_id=1, council_type_id=2 where council_code = 922;
update petel_schema.councils set long_name ='מועצה מקומית  רמת ישי', district_id=7, council_type_id=2 where council_code = 122;
update petel_schema.councils set long_name ='מועצה מקומית  שבלי - אום אל-גנם', district_id=7, council_type_id=2 where council_code = 913;
update petel_schema.councils set long_name ='מועצה מקומית  שגב-שלום', district_id=2, council_type_id=2 where council_code = 1286;
update petel_schema.councils set long_name ='מועצה מקומית  שוהם', district_id=4, council_type_id=2 where council_code = 1304;
update petel_schema.councils set long_name ='מועצה מקומית  שלומי', district_id=7, council_type_id=2 where council_code = 812;
update petel_schema.councils set long_name ='מועצה מקומית  שעב', district_id=7, council_type_id=2 where council_code = 538;
update petel_schema.councils set long_name ='מועצה מקומית  תל מונד', district_id=4, council_type_id=2 where council_code = 154;
update petel_schema.councils set long_name ='מועצה מקומית  תל שבע', district_id=2, council_type_id=2 where council_code = 1054;
update petel_schema.councils set long_name ='מועצה מקומית  מגדל תפן', district_id=7, council_type_id=2 where council_code = 1722;
update petel_schema.councils set long_name ='מועצה מקומית  נאות חובב', district_id=2, council_type_id=2 where council_code = 1770;
update petel_schema.councils set long_name ='מועצה מקומית  צור הדסה', district_id=5, council_type_id=2 where council_code = 1113;
update petel_schema.councils set long_name ='מועצה מקומית  שער שומרון', district_id=5, council_type_id=2 where council_code = 3826;
update petel_schema.councils set long_name ='מועצה אזורית  אל-בטוף', district_id=7, council_type_id=3 where council_code = 5565;
update petel_schema.councils set long_name ='מועצה אזורית  אל קסום', district_id=2, council_type_id=3 where council_code = 5569;
update petel_schema.councils set long_name ='מועצה אזורית  אלונה', district_id=1, council_type_id=3 where council_code = 5545;
update petel_schema.councils set long_name ='מועצה אזורית  אשכול', district_id=2, council_type_id=3 where council_code = 5538;
update petel_schema.councils set long_name ='מועצה אזורית  באר טוביה', district_id=2, council_type_id=3 where council_code = 5533;
update petel_schema.councils set long_name ='מועצה אזורית  בוסתן אל-מרג''', district_id=7, council_type_id=3 where council_code = 5566;
update petel_schema.councils set long_name ='מועצה אזורית  בני שמעון', district_id=2, council_type_id=3 where council_code = 5541;
update petel_schema.councils set long_name ='מועצה אזורית  ברנר', district_id=4, council_type_id=3 where council_code = 5528;
update petel_schema.councils set long_name ='מועצה אזורית  גדרות', district_id=4, council_type_id=3 where council_code = 5532;
update petel_schema.councils set long_name ='מועצה אזורית  גולן', district_id=7, council_type_id=3 where council_code = 5571;
update petel_schema.councils set long_name ='מועצה אזורית  גוש עציון', district_id=5, council_type_id=3 where council_code = 5576;
update petel_schema.councils set long_name ='מועצה אזורית  גזר', district_id=4, council_type_id=3 where council_code = 5530;
update petel_schema.councils set long_name ='מועצה אזורית  גן רווה', district_id=4, council_type_id=3 where council_code = 5527;
update petel_schema.councils set long_name ='מועצה אזורית  דרום השרון', district_id=4, council_type_id=3 where council_code = 5520;
update petel_schema.councils set long_name ='מועצה אזורית  הגלבוע', district_id=7, council_type_id=3 where council_code = 5508;
update petel_schema.councils set long_name ='מועצה אזורית  הגליל העליון', district_id=7, council_type_id=3 where council_code = 5501;
update petel_schema.councils set long_name ='מועצה אזורית  הגליל התחתון', district_id=7, council_type_id=3 where council_code = 5503;
update petel_schema.councils set long_name ='מועצה אזורית  הערבה התיכונה', district_id=2, council_type_id=3 where council_code = 5554;
update petel_schema.councils set long_name ='מועצה אזורית  הר חברון', district_id=5, council_type_id=3 where council_code = 5578;
update petel_schema.councils set long_name ='מועצה אזורית  זבולון', district_id=1, council_type_id=3 where council_code = 5512;
update petel_schema.councils set long_name ='מועצה אזורית  חבל אילות', district_id=2, council_type_id=3 where council_code = 5553;
update petel_schema.councils set long_name ='מועצה אזורית  חבל יבנה', district_id=4, council_type_id=3 where council_code = 5529;
update petel_schema.councils set long_name ='מועצה אזורית  חבל מודיעין', district_id=4, council_type_id=3 where council_code = 5525;
update petel_schema.councils set long_name ='מועצה אזורית  חוף אשקלון', district_id=2, council_type_id=3 where council_code = 5536;
update petel_schema.councils set long_name ='מועצה אזורית  חוף הכרמל', district_id=1, council_type_id=3 where council_code = 5515;
update petel_schema.councils set long_name ='מועצה אזורית  חוף השרון', district_id=4, council_type_id=3 where council_code = 5519;
update petel_schema.councils set long_name ='מועצה אזורית  יואב', district_id=2, council_type_id=3 where council_code = 5535;
update petel_schema.councils set long_name ='מועצה אזורית  לב השרון', district_id=4, council_type_id=3 where council_code = 5518;
update petel_schema.councils set long_name ='מועצה אזורית  לכיש', district_id=2, council_type_id=3 where council_code = 5550;
update petel_schema.councils set long_name ='מועצה אזורית  מבואות החרמון', district_id=7, council_type_id=3 where council_code = 5555;
update petel_schema.councils set long_name ='מועצה אזורית  מגידו', district_id=7, council_type_id=3 where council_code = 5513;
update petel_schema.councils set long_name ='מועצה אזורית  מגילות ים המלח', district_id=5, council_type_id=3 where council_code = 5574;
update petel_schema.councils set long_name ='מועצה אזורית  מטה אשר', district_id=7, council_type_id=3 where council_code = 5504;
update petel_schema.councils set long_name ='מועצה אזורית  מטה בנימין', district_id=5, council_type_id=3 where council_code = 5573;
update petel_schema.councils set long_name ='מועצה אזורית  מטה יהודה', district_id=6, council_type_id=3 where council_code = 5526;
update petel_schema.councils set long_name ='מועצה אזורית  מנשה', district_id=1, council_type_id=3 where council_code = 5514;
update petel_schema.councils set long_name ='מועצה אזורית  מעלה יוסף', district_id=7, council_type_id=3 where council_code = 5552;
update petel_schema.councils set long_name ='מועצה אזורית  מרום הגליל', district_id=7, council_type_id=3 where council_code = 5502;
update petel_schema.councils set long_name ='מועצה אזורית  מרחבים', district_id=2, council_type_id=3 where council_code = 5542;
update petel_schema.councils set long_name ='מועצה אזורית  משגב', district_id=7, council_type_id=3 where council_code = 5556;
update petel_schema.councils set long_name ='מועצה אזורית  נווה מדבר', district_id=2, council_type_id=3 where council_code = 5568;
update petel_schema.councils set long_name ='מועצה אזורית  נחל שורק', district_id=4, council_type_id=3 where council_code = 5531;
update petel_schema.councils set long_name ='מועצה אזורית  עמק הירדן', district_id=7, council_type_id=3 where council_code = 5506;
update petel_schema.councils set long_name ='מועצה אזורית  עמק המעיינות', district_id=7, council_type_id=3 where council_code = 5507;
update petel_schema.councils set long_name ='מועצה אזורית  עמק חפר', district_id=4, council_type_id=3 where council_code = 5516;
update petel_schema.councils set long_name ='מועצה אזורית  עמק יזרעאל', district_id=7, council_type_id=3 where council_code = 5509;
update petel_schema.councils set long_name ='מועצה אזורית  ערבות הירדן', district_id=5, council_type_id=3 where council_code = 5575;
update petel_schema.councils set long_name ='מועצה אזורית  רמת נגב', district_id=2, council_type_id=3 where council_code = 5548;
update petel_schema.councils set long_name ='מועצה אזורית  שדות דן', district_id=4, council_type_id=3 where council_code = 5540;
update petel_schema.councils set long_name ='מועצה אזורית  שדות נגב', district_id=2, council_type_id=3 where council_code = 5539;
update petel_schema.councils set long_name ='מועצה אזורית  שומרון', district_id=5, council_type_id=3 where council_code = 5572;
update petel_schema.councils set long_name ='מועצה אזורית  שער הנגב', district_id=2, council_type_id=3 where council_code = 5537;
update petel_schema.councils set long_name ='מועצה אזורית  שפיר', district_id=2, council_type_id=3 where council_code = 5534;
update petel_schema.councils set long_name ='מועצה אזורית  תמר', district_id=2, council_type_id=3 where council_code = 5551;
